<a href="https://colab.research.google.com/github/" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Question 1 - Weather Data Analysis

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

weather_data = {
    'Date': ['01-01-2025','02-01-2025','03-01-2025','04-01-2025','05-01-2025',
             '06-01-2025','07-01-2025','08-01-2025','09-01-2025','10-01-2025'],
    'Temperature': [15.2, 16.8, 14.5, 13.0, 17.6, 18.1, 16.2, 12.4, 13.8, 15.5],
    'Humidity': [80, 75, 85, 90, 70, 65, 78, 88, 83, 79],
    'Wind_Speed': [10.5, 8.0, 12.0, 15.2, 7.4, 6.0, 9.1, 14.3, 11.5, 10.0],
    'Rainfall': [0, 0, 1.2, 5.4, 0, 0, 0.5, 2.1, 0, 0]
}
df = pd.DataFrame(weather_data)
df['Date'] = pd.to_datetime(df['Date'], format='%d-%m-%Y')

# a. Check for missing values and handle them
print("Missing values:\n", df.isnull().sum())
df.fillna(df.mean(numeric_only=True), inplace=True)
print("\nAfter handling missing values:\n", df)

Missing values:
 Date           0
Temperature    0
Humidity       0
Wind_Speed     0
Rainfall       0
dtype: int64

After handling missing values:
         Date  Temperature  Humidity  Wind_Speed  Rainfall
0 2025-01-01         15.2        80        10.5       0.0
1 2025-01-02         16.8        75         8.0       0.0
2 2025-01-03         14.5        85        12.0       1.2
3 2025-01-04         13.0        90        15.2       5.4
4 2025-01-05         17.6        70         7.4       0.0
5 2025-01-06         18.1        65         6.0       0.0
6 2025-01-07         16.2        78         9.1       0.5
7 2025-01-08         12.4        88        14.3       2.1
8 2025-01-09         13.8        83        11.5       0.0
9 2025-01-10         15.5        79        10.0       0.0


In [1]:
# b. Calculate the average temperature for each month
df['Month'] = df['Date'].dt.month
monthly_avg = df.groupby('Month')['Temperature'].mean()
print("Monthly Average Temperature:\n", monthly_avg)

Monthly Average Temperature:
 Month
1    15.31
Name: Temperature, dtype: float64


In [1]:
# c. Visualize the monthly average temperature using a bar plot
plt.figure(figsize=(8,5))
monthly_avg.plot(kind='bar', color='steelblue')
plt.title('Monthly Average Temperature')
plt.xlabel('Month')
plt.ylabel('Average Temperature (°C)')
plt.tight_layout()
plt.show()

## Question 2 - Student Performance Analysis

In [1]:
import pandas as pd
import numpy as np

data = {
    'Student_ID': [101,102,103,104,105,106,107,108,109,110],
    'Name': ['Alice Brown','Ben Carter','Clara Davis','David Evans','Eva Foster',
             'Frank Green','Grace Hall','Henry Ives','Isla Jones','Jack King'],
    'Maths': [85,78,92,65,74,60,88,70,95,82],
    'Physics': [88,75,94,68,78,55,85,72,96,80],
    'Chemistry': [87,80,90,66,76,58,86,74,94,78]
}
df = pd.DataFrame(data)

# a. Summary statistics for each subject
print("Summary Statistics:\n", df[['Maths','Physics','Chemistry']].describe())

Summary Statistics:
            Maths    Physics  Chemistry
count  10.000000  10.000000  10.000000
mean   78.900000  79.100000  78.900000
std    11.618472  12.449453  11.080012
min    60.000000  55.000000  58.000000
25%    71.000000  72.750000  74.500000
50%    80.000000  79.000000  79.000000
75%    87.250000  87.250000  86.750000
max    95.000000  96.000000  94.000000


In [1]:
# b. Calculate the average score for each student
df['Average'] = df[['Maths','Physics','Chemistry']].mean(axis=1)
print("Average score for each student:\n", df[['Name','Average']])

Average score for each student:
           Name    Average
0  Alice Brown  86.666667
1   Ben Carter  77.666667
2  Clara Davis  92.000000
3  David Evans  66.333333
4   Eva Foster  76.000000
5  Frank Green  57.666667
6   Grace Hall  86.333333
7   Henry Ives  72.000000
8   Isla Jones  95.000000
9    Jack King  80.000000


In [1]:
# c. Identify students who scored below 60 in more than two subjects
below60 = (df[['Maths','Physics','Chemistry']] < 60).sum(axis=1)
result = df[below60 > 2][['Name']]
print("Students who scored below 60 in more than two subjects:\n", result)

Students who scored below 60 in more than two subjects:
 Empty DataFrame
Columns: [Name]
Index: []


## Question 3 - Flight Data Analysis

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(42)
airlines = ['IndiGo','Air India','SpiceJet','Vistara','GoAir']
origins = ['DEL','BOM','MAA','BLR','HYD']
destinations = ['BOM','DEL','BLR','MAA','CCU']

n = 50
flight_data = {
    'Airline': np.random.choice(airlines, n),
    'Origin': np.random.choice(origins, n),
    'Destination': np.random.choice(destinations, n),
    'Departure_Delay': np.random.randint(-10, 120, n)
}
df = pd.DataFrame(flight_data)

# a. Summary statistics for departure delays
print("Summary statistics for departure delays:\n", df['Departure_Delay'].describe())

Summary statistics for departure delays:
 count     50.000000
mean      72.200000
std       38.768807
min       -9.000000
25%       42.250000
50%       83.500000
75%      105.000000
max      119.000000
Name: Departure_Delay, dtype: float64


In [1]:
# b. Average delay for each airline
avg_delay = df.groupby('Airline')['Departure_Delay'].mean()
print("Average delay for each airline:\n", avg_delay)

Average delay for each airline:
 Airline
Air India    72.900000
GoAir        83.700000
IndiGo       64.000000
SpiceJet     56.300000
Vistara      79.461538
Name: Departure_Delay, dtype: float64


In [1]:
# c. Most common departure and arrival destinations
print("Most common departure destination:", df['Origin'].value_counts().idxmax())
print("Most common arrival destination:", df['Destination'].value_counts().idxmax())

Most common departure destination: BLR
Most common arrival destination: MAA


In [1]:
# d. Box plot of departure delays
plt.figure(figsize=(8,5))
plt.boxplot(df['Departure_Delay'], vert=True, patch_artist=True,
            boxprops=dict(facecolor='steelblue'))
plt.title('Distribution of Departure Delays')
plt.ylabel('Departure Delay (minutes)')
plt.tight_layout()
plt.show()

## Question 4 - Euclidean Distance and Dot Product

In [1]:
import numpy as np

# Euclidean Distance for two points in 2D space
p1 = np.array([1, 2])
p2 = np.array([4, 6])
euclidean_dist = np.sqrt(np.sum((p2 - p1)**2))
print("Point 1:", p1)
print("Point 2:", p2)
print("Euclidean Distance:", euclidean_dist)

# Dot Product for two matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
dot_product = np.dot(A, B)
print("\nMatrix A:\n", A)
print("Matrix B:\n", B)
print("Dot Product (A . B):\n", dot_product)

Point 1: [1 2]
Point 2: [4 6]
Euclidean Distance: 5.0

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Dot Product (A . B):
 [[19 22]
 [43 50]]


## Question 5 - Time Series Data: Daily Temperatures

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

np.random.seed(42)
dates = pd.date_range(start='2024-01-01', periods=365, freq='D')
temps = 20 + 10 * np.sin(np.linspace(0, 2*np.pi, 365)) + np.random.randn(365) * 2

df = pd.DataFrame({'Date': dates, 'Temperature': temps})
df.set_index('Date', inplace=True)

print("First 5 rows:\n", df.head())
print("\nBasic Statistics:\n", df.describe())

First 5 rows:
             Temperature
Date                   
2024-01-01    20.993428
2024-01-02    19.896078
2024-01-03    21.640538
2024-01-04    23.563673
2024-01-05    20.221605

Basic Statistics:
        Temperature
count   365.000000
mean     20.019893
std       7.242015
min       3.697190
25%      13.378202
50%      20.277570
75%      26.464471
max      34.214047


In [1]:
monthly_avg = df.resample('ME').mean()
print("Monthly Average Temperature:\n", monthly_avg)

Monthly Average Temperature:
             Temperature
Date                   
2024-01-31    22.127009
2024-02-29    26.727719
2024-03-31    29.537973
2024-04-30    29.586391
2024-05-31    26.850824
2024-06-30    23.116661
2024-07-31    17.783546
2024-08-31    12.904098
2024-09-30    10.180194
2024-10-31    10.621211
2024-11-30    13.660868
2024-12-31    17.375637


In [1]:
rolling_avg = df['Temperature'].rolling(window=7).mean()

plt.figure(figsize=(12,5))
plt.plot(df.index, df['Temperature'], label='Daily Temp', alpha=0.5)
plt.plot(df.index, rolling_avg, label='7-Day Rolling Avg', color='red')
plt.title('Daily Temperature over a Year')
plt.xlabel('Date')
plt.ylabel('Temperature (°C)')
plt.legend()
plt.tight_layout()
plt.show()

## Question 6 - Stock Price Simulation and Analysis

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

np.random.seed(42)
dates = pd.date_range(start='2024-01-01', periods=365, freq='D')
initial_price = 100
returns = np.random.normal(loc=0.001, scale=0.02, size=365)
prices = initial_price * np.cumprod(1 + returns)

df = pd.DataFrame({'Date': dates, 'Price': prices})
df.set_index('Date', inplace=True)

print("Stock Price Statistics:\n", df.describe())

Stock Price Statistics:
             Price
count  365.000000
mean   107.856872
std     19.014138
min     82.179590
25%     90.430208
50%    104.182455
75%    120.549893
max    149.874523


In [1]:
df['MA_7'] = df['Price'].rolling(window=7).mean()
df['MA_30'] = df['Price'].rolling(window=30).mean()

print("First 10 rows with Moving Averages:\n", df.head(10))

First 10 rows with Moving Averages:
                  Price        MA_7  MA_30
Date                                     
2024-01-01  101.093428         NaN    NaN
2024-01-02  100.914969         NaN    NaN
2024-01-03  102.323114         NaN    NaN
2024-01-04  105.542260         NaN    NaN
2024-01-05  105.153541         NaN    NaN
2024-01-06  104.766288         NaN    NaN
2024-01-07  108.180019  103.996231    NaN
2024-01-08  109.948621  105.261259    NaN
2024-01-09  109.026209  106.420007    NaN
2024-01-10  110.318300  107.562177    NaN


In [1]:
plt.figure(figsize=(12,5))
plt.plot(df.index, df['Price'], label='Stock Price', alpha=0.7)
plt.plot(df.index, df['MA_7'], label='7-Day MA', color='orange')
plt.plot(df.index, df['MA_30'], label='30-Day MA', color='red')
plt.title('Daily Stock Price with Moving Averages')
plt.xlabel('Date')
plt.ylabel('Price ($)')
plt.legend()
plt.tight_layout()
plt.show()

## Question 7 - Fruits DataFrame Operations

In [1]:
import pandas as pd

# a. Create lists and DataFrame
data = ['Apple', 'Banana', 'Cherry', 'Date', 'Elderberry']
prices = [1.5, 0.5, 3.0, 2.0, 4.5]

fruits_df = pd.DataFrame(list(zip(data, prices)), columns=['Fruit', 'Price'])
print("DataFrame created:\n", fruits_df)

DataFrame created:
         Fruit  Price
0       Apple    1.5
1      Banana    0.5
2      Cherry    3.0
3        Date    2.0
4  Elderberry    4.5


In [1]:
# b. info()
print("DataFrame Info:")
fruits_df.info()

DataFrame Info:
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Fruit   5 non-null      str    
 1   Price   5 non-null      float64
dtypes: float64(1), str(1)
memory usage: 212.0 bytes


In [1]:
# c. Print using to_string()
print("\nFull DataFrame:\n", fruits_df.to_string())


Full DataFrame:
         Fruit  Price
0       Apple    1.5
1      Banana    0.5
2      Cherry    3.0
3        Date    2.0
4  Elderberry    4.5


In [1]:
# d. Descriptive statistics for Price
print("\nDescriptive Statistics for Price column:\n", fruits_df['Price'].describe())


Descriptive Statistics for Price column:
 count    5.000000
mean     2.300000
std      1.524795
min      0.500000
25%      1.500000
50%      2.000000
75%      3.000000
max      4.500000
Name: Price, dtype: float64
