In [ ]:
import numpy as np
arr=np.array([[1,2,0,4],[4,-0.5,6,0],[2.6,0,7,8],[3,-7,4,2.0]])
print("Original array:\n",arr)

Original array:
 [[ 1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]


In [ ]:
print("\nEvery other rows: \n",arr[:3:2])


Every other rows: 
 [[1.  2.  0.  4. ]
 [2.6 0.  7.  8. ]]


In [ ]:
arr=np.array([1,2,3,4,5,6,7])
print("\nOriginal array:",arr)
print("\nReturns every other elements in the array : [::2]:",arr[::2])


Original array: [1 2 3 4 5 6 7]

Returns every other elements in the array : [::2]: [1 3 5 7]


In [ ]:

temp=arr[:2,:3]
print("\nArray with first 2 rows and 3 columns:\n",temp)


Array with first 2 rows and 3 columns:
 [[ 1.   2.   0. ]
 [ 4.  -0.5  6. ]]


In [ ]:
cond=arr>2
temp=arr[cond]
print("\nElements greater than 2:\n",temp)


Elements greater than 2:
 [3 4 5 6 7]


In [ ]:
import numpy as np
arr = np.array([[-1, 2, 0, 4], [4, -0.5, 6, 0], [2.6, 0, 7, 8], [3, -7, 4, 2.0]])
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print("Orginal arrays:\n",arr1,arr2)
print("\nJoined array:\n",arr)

Orginal arrays:
 [1 2 3] [4 5 6]

Joined array:
 [1 2 3 4 5 6]


In [ ]:
arr=np.hstack((arr1,arr2))
print("\nHorizontal joining:\n",arr)


Horizontal joining:
 [1 2 3 4 5 6]


In [ ]:
arr=np.vstack((arr1,arr2))
print("\nVertical joining:\n",arr)


Vertical joining:
 [[1 2 3]
 [4 5 6]]


In [ ]:
arr=np.dstack((arr1,arr2))
print("\nDepth joining:\n",arr)


Depth joining:
 [[[1 4]
  [2 5]
  [3 6]]]


In [ ]:
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print("Orginal Array:\n",arr)
print("\nSplitted array:\n",newarr)
print(("\nSplitted array in another form:\n"))
print(newarr[0])
print(newarr[1])
print(newarr[2])

Orginal Array:
 [1 2 3 4 5 6]

Splitted array:
 [array([1, 2]), array([3, 4]), array([5, 6])]

Splitted array in another form:

[1 2]
[3 4]
[5 6]
